NOAA-GSL/ExascaleWorkflowSandbox

- .github/workflows/docker-slurm.yml
- docker/frontend/Dockerfile
- docker/master/Dockerfile
- docker/node/Dockerfile
Update Dockerfiles and CI workflow to remove loading of Flux Spack environment.  These containers are designed to run with Flux and Parsl so it makes sense to load the Spack flux environment at login rather than having to do it manually every time a command is run via `docker exec` or when logging into an interactive session in the frontend container.
In addition, creation of ssh keys is removed from the CI because the upstream base containers were updated such that the keys are already created.  There is no longer a need to create ssh keys.
> Load Flux Spack environment automatically at login

- docker/frontend/Dockerfile
- docker/install/install_base.sh
- docker/install/install_bootstrap.sh
- docker/install/install_flux_parsl.sh
- docker/install/install_spack.sh
- docker/master/Dockerfile
- docker/node/Dockerfile
The existing install scripts currently in use for building Docker containers are not portable because they assume that `gcc 9.4.0` is already installed on the system.  If that is not the case, the install will fail.  This PR introduces two more installation scripts to help make the install process more portable.  When the required compiler, `gcc 9.4.0`, is not available, a bootstrap compiler must be built and then used to install `gcc 9.4.0` before installing Flux and Parsl.  A `install_bootstrap.sh` install script is added to build and install the bootstrap compiler if one is needed.  This script builds and installs `gcc 9.4.0` with the system default compiler.  However, in order to make Spack build cache mirrors work correctly on potential destination machines with no internet access, …
> Make install scripts portable

- .github/workflows/docker-slurm.yml
- src/chiltepin/config/factory.py
- tests/ci.yaml
- tests/mpi_pi.f90
- tests/test_parsl_flux_mpi_hello.py
This adds a test that ensures MPI programs can run concurrently and do not share resources when doing so.  A `mpi_pi.f90` test program is introduced to assist as it provides a bit more computation for situations requiring a longer run time for testing purposes.  It also exercises MPI collectives so is a bit more rigorous than the "hello" MPI program.
NOTE: The config factory was updated to set the `cores_per_node` property of the Slurm Provider.  Also, the testing fixture needed some modifications because the new tests needs to know how many cores per node there are.  So it was modified to return a dict that allows accessing the configuration and not just the environment settings.
> Add test to ensure concurrent MPI programs don't use overlapping resources

- docker/install/chiltepin.yml
- tests/hera.yaml
This PR adds explicit support for Hera.  A `hera.yaml` config file is added.  Also, it was discovered that the latest Parsl breaks the latest version of Flux that is available via conda.  So we also explicitly set the version of Parsl to the latest one that is compatible with the latest available version of Flux.
> Add Hera support and set versions of Parsl and Flux

- tests/test_parsl_flux_mpi_hello.py
The `test_mpi_hello` test in `tests/test_parsl_flux_mpi_hello.py` only checks that the Parsl App completed with a status of 0 (meaning success). It does not actually check whether the output of the task, written to `parsl_flux_mpi_hello_run.out` is correct. This test needs to be updated to validate the output.
Closes Issue #44
> Add test to test_mpi_hello to validate run output

- .gitignore
Update `.gitignore` to disregard test output from stderr, stdout and others.
Also updated the sorting of the items listed in the `.gitignore`. They know follow an ascending lexicographical order.
> Updated .gitignore including acending lexicographical ordering.

- tests/test_parsl_flux_mpi_hello.py
The test_flux_resource_list test in `tests/test_parsl_flux_mpi_hello.py` only checks that the Parsl App completed with a status of 0 (meaning success). It does not actually check whether the output of the task, written to `parsl_flux_resource_list.out` is correct. This test needs to be updated to validate the output. 
Two things will vary from run to run: 
1. The number of `free nodes`
2. The `NODELIST`, host name that is used
Closes #43
> Add test to test_flux_resource_list does not validate output

- .github/workflows/docker-slurm.yml
- docker/spack-stack/create_dockerfile.sh
- docker/spack-stack/mirrors.in.yaml
This PR adds modifications to the spack-stack Dockerfile creation script and the CI workflow definition that allow pushing of spack binaries to a binary build cache stored an AWS S3 bucket.  This relies on a completed build in order for binaries to be pushed to the cache.  However, once they are there, it will speed building of spack-stack container by orders of magnitude.  The modifications add a template that can be used in conjunction with github secrets to configure the mirror in the container at build time.  The CI and Dockerfile make use of the mirror for pushing packages and using it for retrieving ones already built.
> Add capability to use AWS S3 bucket as a spack binary cache

- .github/workflows/docker-slurm.yml
- docker/frontend/Dockerfile
- docker/master/Dockerfile
- docker/node/Dockerfile
- docker/spack-stack/create_dockerfile.sh
- docker/spack-stack/mirrors.in.yaml
- tests/chiltepin.yaml
- tests/ci.yaml
This PR adds flux and pytest to the spack-stack environment and replaces the conda environment.  It also changes the build cache S3 bucket to one more appropriately (and spelled correctly) named.  Additionally, since the AWS CLI package is one of the packages installed in spack-stack, some additional Dockerfile secrets were needed to get the S3 authentication to work properly (for some reason the `access_pair` in the mirror config wasn't quite enough).
For now, the conda environment is only removed for the container build/tests.  A future PR will address the replacement of conda on HPCs and other non-container systems.
> Add Flux to spack-stack & remove miniconda environment

- tests/output/parsl_flux_mpi_hello_run.out.baseline
- tests/output/parsl_flux_resource_list.txt.baseline
This PR simply removes some old files that are no longer needed now that we have proper pytest functionality.
> Remove old test output baselines that are no longer needed

- .github/workflows/docker-slurm.yml
- docker/spack-stack/create_dockerfile.sh
There is a known bug in Spack/Flux that causes build of Flux core to fail with:
```
#14 11461.8 ==> Installing flux-core-0.58.0-6xqraerbttwveddwgcrrrhhlc2knqeny [260/265]
#14 11461.8 ==> No binary for flux-core-0.58.0-6xqraerbttwveddwgcrrrhhlc2knqeny found: installing from source
#14 11463.4 ==> Fetching https://github.com/flux-framework/flux-core/releases/download/v0.58.0/flux-core-0.58.0.tar.gz
#14 11463.4 ==> No patches needed for flux-core
#14 11463.5 ==> flux-core: Executing phase: 'autoreconf'
#14 11463.5 ==> flux-core: Executing phase: 'configure'
#14 11471.8 ==> Error: ProcessError: Command exited with status 1:
#14 11471.8     '/tmp/root/spack-stage/spack-stage-flux-core-0.58.0-6xqraerbttwveddwgcrrrhhlc2knqeny/spack-src/configure' …
```
> Implement workaround for Flux Spack build problem

- .github/workflows/package-cleanup.yaml
The repository is accumulating very large numbers of untagged packages when the CI runs.  This adds a CI workflow that removes untagged packages to keep the repository packages cleaned up.  Closes #68 .
> Add GitHub workflow to remove untagged container packages

- .github/workflows/package-cleanup.yaml
- docker/docker-compose.yml
This PR uses the `nocopy` attribute for shared mounts in docker compose to remove the race condition caused by multiple containers trying to populate `/home` at startup time.  This change sets the `frontend` container to be the one to write to the volume, and the other containers do not attempt to update `/home` at startup.  This works because the initial contents of `/home` are the same on all containers.  Closes #70
> Fix volume race condition

- tests/test_parsl_flux_mpi_hello.py
There are multiple instances where the `.format()` function is used for inserting variables into triple quoted strings. 
A far better approach is to use triple quote fstrings.
For example, instead of:
```
x = """hello {}""".format(name)
```
it would be better to use:
```
x=f"""hello {name}"""
```
We should fix these and stop using the `.format()` function going forward.
Looking into where the .format() function is used, it seems to be isolated to a single file, `tests/test_parsl_flux_mpi_hello.py`.  I was able to perform a `grep -Ri ".format(" src/ tests/` — for all instances of a piece of text and the result being the code section returned with a hit, and `grep -Ril ".format(" src/ tests/` — for all instances of a piece of text and the resulting filenames that contain the code sections. …
> Replace .format() function with triple quote strings fstrings

- .github/workflows/docker-slurm.yml
- docker/spack-stack/create_dockerfile.sh
- docker/spack-stack/get_sso_credentials.sh
- docker/spack-stack/mirrors.in.yaml
- install/get_sso_credentials.sh
- install/install.sh
This PR updates the CI workflow with new AWS role-based authentication for use with a new S3 bucket in the us-east-2 AWS region.  It also updates the install scripts used for installation on on-prem HPC platforms to take into account the new mechanism for obtaining SSO AWS credentials.  Closes #77.
The CI workflow new uses the `configure-aws-credentials` github action to assume a role that is authorized to access AWS resources from github.  The temporary credentials are configured to last 6 hours, which is the maximum duration of a GitHub Actions CI job.  The action supplies the temporary keys and tokens needed for passing into the Docker builds for pushing to the Spack binary build cache on S3. Due to very slow push times to S3, the CI workflow was split into more jobs (which each have a …
> Migrate S3 Spack build cache to us-east-2

- docker/spack-stack/create_dockerfile.sh
- install/install.sh
This PR adds installation of globus-compute-sdk and globus-compute-endpoint to both the container and HPC Spack Chiltepin environments. Some handling of dependencies was added (for dill mostly) to facilitate this. Dependencies for dill required modification to resolve compatibility issues with Flux.
Closes #81
> Add globus-compute-sdk and globus-compute-endpoint to install steps

- docker/spack-stack/create_dockerfile.sh
- install/install.sh
It was discovered that the version of `pyzmq` that `globus-compute-endpoint` wants to install is not compatible with the version of `libzmq` that is installed by Spack for `flux-sched`.  Running any Parsl program or the `globus-compute-endpoint` command result in an error:
```
ImportError: libzmq.so.5: cannot open shared object file: No such file or directory
```
This PR forces pip to install a newer version of `pyzmq` that works with the `libzmq` installed by Spack.  This does violate specified dependencies for `globus-compute-endpoint` but tests show no issues.
Closes #87
> Force pyzmq==25.1.2 to be installed to overcome incompatibility issues

- install/install.sh
This PR pins the version of Python used in install/install.sh to match the version of Python used in spack-stack. This is important because the versions of tools needs to be consistent across Globus Compute endpoints. Closes https://github.com/NOAA-GSL/ExascaleWorkflowSandbox/issues/89
> Synchronize Python version with version used in spack-stack

- src/chiltepin/jedi/leadtime.py
- tests/test_leadtime.py
The `leadtime.fcst_to_seconds` and `leadtime.seconds_to_fcst` utility functions should be renamed to better reflect what they do. 
`leadtime.fcst_to_seconds` should be renamed to `leadtime.leadtime_to_seconds`.
`leadtime.seconds_to_fcst` should be renamed to `leadtime.seconds_to_leadtime`.
Added unit tests to the utility functions to ensure they work correctly. The tests cover the following scenarios:
"PT0S" <---> 0
"PT1M" <---> 60
"PT1H" <---> 3600
"PT1H30M" <---> 5400
"P1D" <---> 86400
"P1DT1H" <---> 90000
"P1DT1H30M" <---> 91800
"MT0S" <---> 0
"MT1M" <---> -60
"MT1H" <---> -3600
"MT1H30M" <--> -5400
"M1D" <--->  -86400
"M1DT1H" <---> -90000
"M1DT1H30M"<--->  -91800
closes #86
> Leadtime utility functions renamed and unit tests added.

- .github/workflows/package-cleanup.yaml
This PR simply updates the version of the `actions/delete-package-versions` action used in the CI workflow to version 5. Fixes #102.
> Update to actions/delete-package-versions@v5

- docker/spack-stack/create_dockerfile.sh
- install/install.sh
- tests/test_uwtools.py
The uwtools Python Package has been installed to the container and the Chiltepin Spack environment on the HPC Systems. 
Closes #97
> Add uwtools Python package

- tests/config.yaml
This updates the Hera config file to reflect the new location of spack-stack after the Rocky8 transition was completed.
> Update Hera config for new spack-stack location

- docker/spack-stack/Dockerfile.patch
- requirements.txt
- A new bugfix release for uwtools has come out that addresses fixing leadtime logic when processing 0-hr forecast.
> Update uwtools version

- apps/mpas/bin/experiment.py
- src/chiltepin/jedi/qg/wrapper.py
- src/chiltepin/metis/wrapper.py
- src/chiltepin/mpas/limited_area/wrapper.py
- src/chiltepin/mpas/wrapper.py
- src/chiltepin/wps/wrapper.py
The new versions of Parsl have removed support for `parsl_resource_specification` from HTEX Executors so this PR removes it from the wrappers that use it.
> Remove parsl resource specification from QG wrappers

- apps/mpas/bin/experiment.py
- src/chiltepin/jedi/qg/wrapper.py
- src/chiltepin/metis/wrapper.py
- src/chiltepin/mpas/limited_area/wrapper.py
- src/chiltepin/mpas/wrapper.py
- src/chiltepin/tasks.py
- src/chiltepin/wps/wrapper.py
- src/chiltepin/wrf/wrapper.py
- tests/test_qg_install.py
This PR adds task decorators: `@python_task`, `@bash_task`, and `@join_task`.  These decorators return corresponding Parsl Apps but offer two important enhancements.  First, the new task decorators can be used for class methods that use `self` to access object state. Second, they allow the tasks to be run on executors that are chosen at runtime.
Closes #124
> Add Chiltepin task decorators

- src/chiltepin/cli.py
- src/chiltepin/configure.py
- src/chiltepin/endpoint.py
- tests/delete-endpoint.py
- tests/test_endpoint.py
- tests/test_globus_compute_hello.py
- tests/test_globus_compute_mpi.py
This update adds a new CLI and a corresponding API for managing Globus Compute endpoints.  The API runs the corresponding `globus-compute-endpoint` commands as a subprocess and may be called from other parts of the code when endpoints need to be configured/started/stopped/deleted.  The CLI introduces a new `chiltepin endpoint` command for managing the endpoints.  It calls the corresponding API routines.  While a bit redundant with the `globus-compute-endpoint` CLI, it allows hiding of certain behaviors we don't want to expose to the user.  Those will become more evident when multi-user endpoints are introduced.
Closes #134 and #137
> Add an endpoint API and CLI for manipulating globus compute endpoints

- apps/mpas/bin/experiment.py
- apps/mpas/config/default_config.yaml
- pyproject.toml
- src/chiltepin/configure.py
- src/chiltepin/data.py
- src/chiltepin/endpoint.py
This update bumps the Parsl version from a test branch to the official 2026.01.20 release that includes support for the new GlobusComputeExecutor.
The latest `globus-compute-endpoint` and `globus-compute-sdk` packages do not support that version of Parsl, however.  To accommodate the new Parsl, the install dependencies were also updated to install `globus-compute-endpoint` and `globus-compute-sdk` from the `main` branch on Github.  That is a temporary condition that will be fixed in a later PR once new versions of those packages are officially released.
Closes #141
> Update Parsl dependency to 2025.01.20
